### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by masonlouchart**
This commit sets the minimal requirement of Polymer to the version 1.9
(instead of the 1.4).

### CODE REVIEW

**Comment by masonlouchart** [comment]
There's still an issue with the demo page. The demo is working but the snippet is not visible.

Ref: PolymerElements/iron-demo-helpers#54

**Comment by sbeleidy** [comment]
Can you also update the version number so after merging we can push a release?

**Comment by masonlouchart** [comment]
Usually I prefer merge the PRs before make a new release. It avoids to create the release with a merge commit and it ensure the version number is always incremented from the master branch.

All this is depending your Git strategy, so I'll follow yours.

**Comment by masonlouchart** [comment]
Please tell me if I did something wrong or not following your habits.

**Comment by sbeleidy** [comment]
Either way works I just figured this would be easier. I assumed this would be the only thing for the next release so why not.

**Comment by sbeleidy** [comment]
Should we wait for the fix in the demo or just merge this so login-fire can use it? What do you think?

**Comment by masonlouchart** [comment]
Because the release is ready we can merge.

Moreover, the issue seems known and not coming from our element. The element is pretty simple, an snippet inside the documentation would be enough for now. Of course, we have to fix it relatively quickly.

_NB: the priority for me is the login-fire element_

**Pull request merged**
